M48
; DRILL file {KiCad (6.0.1-0)} date 2022 March 11, Friday 16:57:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-03-11T16:57:53+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.600
%
G90
G05
T1
X74.3Y-132.0
X74.3Y-175.0
X117.3Y-132.0
X117.3Y-175.0
T2
X105.25Y-132.588
T0
M30
